/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Insertionsort */

#ifndef _Included_Insertionsort
#define _Included_Insertionsort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Insertionsort
 * Method:    sort
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_Insertionsort_sort
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
