/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Insertionsort */

#ifndef _Included_Insertionsort
#define _Included_Insertionsort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Insertionsort
 * Method:    insertSort
 * Signature: ([IF)I
 */
JNIEXPORT jint JNICALL Java_Insertionsort_insertSort
  (JNIEnv *, jobject, jintArray, jfloat);

#ifdef __cplusplus
}
#endif
#endif
